name: Building recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  MANIFEST: https://github.com/SHRP/manifest.git
  MANIFEST_BRANCH: v3_11.0
  DEVICE: f62
  DT_LINK: https://github.com/aswin11234/device_samsung_f62
  DT_PATH: device/samsung/f62
  TARGET: recoveryimage
  TZ: Asia/Kuching
  BOTTOKEN: ${{ secrets.bottoken }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master


       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main
         

       - name: Initializing environment
         run: |
            git config --global user.name "aswin11234"
            git config --global user.email "aswinsanker08@gmail.com"
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex curl bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            df -h

       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST -b $MANIFEST_BRANCH --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             sudo ln -sf /usr/bin/python2 /usr/bin/python

       - name: Build
         run: |
              cd work
              . build/envsetup.sh &&lunch twrp_f62-eng &&export ALLOW_MISSING_DEPENDENCIES=true && mka recoveryimage
             
       - name: Upload to tg
         run: |
              cd work/out/target/product/f62/
              for i in *.zip; do curl -F document=@"$i" https://api.telegram.org/bot$BOTTOKEN/sendDocument?chat_id=-1001774055317; done
